spring.application.name=blog-management


#spring.datasource.url = jdbc:postgresql://localhost:5432/demo
#spring.datasource.username = postgres
#spring.datasource.password=7412
#
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.hikari.data-source-properties.sslmode=require





spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.kdhhjwexlazbrqmhjyyn
spring.datasource.password=3buN$tUkKG_XdK-
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
management.endpoints.web.exposure.include=health,info,metrics,beans,env,loggers
management.endpoint.health.show-details=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shobhitverma038@gmail.com
spring.mail.password: arta oecs zvwz ppov
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

gemini.api.key = AIzaSyAnb-YLtLOibhbK8WZkruIZrNIWJCXur14
gemini.model = gemini-2.5-flash
#gemini.image.model=gemini-1.5-flash
#gemini.base.url=https://generativelanguage.googleapis.com/v1/models/
